[
 {
        "toyName": "Chasing Mouse Toy",
        "animal": "Cat",
        "picture": "https://img.freepik.com/free-photo/funny-cat-3d-illustration_183364-80273.jpg?size=626&ext=jpg&fbclid=IwAR2uRhf1ziXaYGhsUqlRkFJl0Jh0QmhyffSEwy6BHSxXCJ5kv9gueP1ELyU",
        "sellerEmail": "seller1@example.com",
        "price": 5.99,
        "subcategory": "Interactive Toys",
        "rating": 4.3,
        "availableQuantity": 35,
        "detailDescription": "Keep your cat entertained with the Chasing Mouse Toy. The unpredictable movements of the mouse-shaped toy mimic real prey, triggering your cat's hunting instincts and providing hours of playtime."
    },
    {
        "toyName": "Galloping Stallion Figure",
        "animal": "Horse",
        "picture": "https://img.freepik.com/free-vector/pretty-brown-horse-white-background_1308-110204.jpg?size=626&ext=jpg&ga=GA1.2.1614607020.1683036746&semt=ais",
        "sellerEmail": "seller2@example.com",
        "price": 14.99,
        "subcategory": "Action Toys",
        "rating": 4.8,
        "availableQuantity": 15,
        "detailDescription": "Let your child's imagination run wild with the Galloping Stallion Figure. This detailed horse figure can be posed in different positions, inspiring creative play and storytelling."
    },
    {
        "toyName": "Roaring T-Rex Dinosaur",
        "animal": "Dinosaur",
        "picture": "https://example.com/trex_toy.jpghttps://img.freepik.com/premium-vector/cartoon-green-dinosaur_29190-5005.jpg?size=626&ext=jpg&ga=GA1.1.1614607020.1683036746&semt=ais",
        "sellerEmail": "seller3@example.com",
        "price": 19.99,
        "subcategory": "Plush Toys",
        "rating": 4.7,
        "availableQuantity": 10,
        "detailDescription": "Step back in time with the Roaring T-Rex Dinosaur. This electronic toy features realistic roaring sounds and movable limbs, providing a thrilling prehistoric adventure for dinosaur enthusiasts."
    },
    {
        "toyName": "Peek-a-Boo Panda Plush",
        "animal": "Panda",
        "picture": "https://img.freepik.com/premium-vector/cartoon-panda-eating-bamboo_29190-797.jpg?size=626&ext=jpg&ga=GA1.2.1614607020.1683036746&semt=ais",
        "sellerEmail": "seller4@example.com",
        "price": 13.99,
        "subcategory": "Plush Toys",
        "rating": 4.4,
        "availableQuantity": 25,
        "detailDescription": "Experience the joy of Peek-a-Boo with the Panda Plush. This adorable toy hides its face and then pops out, delighting children and providing endless entertainment."
    },
    {
        "toyName": "Crawling Baby Turtle Toy",
        "animal": "Turtle",
        "picture": "https://img.freepik.com/premium-photo/turtle-isolated-white-file-contains-with-clipping-paths-so-it-is-easy-work_24076-459.jpg?size=626&ext=jpg&fbclid=IwAR133jOnaIOmRONEjVjpdXADU4JTVj07SHmIuTtgEGJ4rWhwcpZ1gynIjO0",
        "sellerEmail": "seller1@example.com",
        "price": 17.99,
        "subcategory": "Water Toys",
        "rating": 4.6,
        "availableQuantity": 12,
        "detailDescription": "Encourage your little one's crawling abilities with the Crawling Baby Turtle Toy. This interactive toy features a crawling motion and colorful lights, stimulating your baby's curiosity and motor skills."
    },
    {
        "toyName": "Hopping Kangaroo Plush",
        "animal": "Kangaroo",
        "picture": "https://img.freepik.com/premium-vector/cartoon-happy-kangaroos-with-baby-joey_29190-4479.jpg?size=626&ext=jpg&ga=GA1.1.1614607020.1683036746&semt=ais",
        "sellerEmail": "seller1@example.com",
        "price": 16.99,
        "subcategory": "Plush Toys",
        "rating": 4.5,
        "availableQuantity": 18,
        "detailDescription": "Bounce into fun with the Hopping Kangaroo Plush. This adorable plush toy mimics the hopping motion of a kangaroo, making it a delightful play companion for children."
    },
    {
        "toyName": "Swimming Turtle Bath Toy",
        "animal": "Turtle",
        "picture": "https://img.freepik.com/free-vector/boy-laying-dinosaur-swimming-ring-water-isolated_1308-58843.jpg?size=626&ext=jpg&ga=GA1.1.1614607020.1683036746&semt=ais",
        "sellerEmail": "seller2@example.com",
        "price": 9.99,
        "subcategory": "Water Toys",
        "rating": 4.3,
        "availableQuantity": 22,
        "detailDescription": "Make bath time a splashing adventure with the Swimming Turtle Bath Toy. This toy swims in water, creating a fun and interactive experience for kids while they enjoy their bath."
    },
    {
        "toyName": "Leaping Frog Jumping Game",
        "animal": "Frog",
        "picture": "https://img.freepik.com/free-vector/hand-painted-smiley-frog-illustration_52683-62166.jpg?size=626&ext=jpg&ga=GA1.2.1614607020.1683036746",
        "sellerEmail": "seller3@example.com",
        "price": 12.99,
        "subcategory": "Activity Toys",
        "rating": 4.6,
        "availableQuantity": 15,
        "detailDescription": "Join the Leaping Frog Jumping Game and challenge your friends to a hopping race. Press the button, and the frogs will start jumping forward. It's a great game for indoor or outdoor play."
    },
    {
        "toyName": "Squeaking Elephant Plush",
        "animal": "Elephant",
        "picture": "https://img.freepik.com/premium-vector/cute-koala-tree-with-brid_490702-13.jpg?size=626&ext=jpg&ga=GA1.1.1614607020.1683036746",
        "sellerEmail": "seller4@example.com",
        "price": 11.99,
        "subcategory": "Plush Toys",
        "rating": 4.7,
        "availableQuantity": 20,
        "detailDescription": "Snuggle up with the Squeaking Elephant Plush. This cuddly toy features a squeaker inside, providing an extra element of fun and stimulation for little ones."
    },
    {
        "toyName": "Dancing Dolphin Bath Toy",
        "animal": "Dolphin",
        "picture": "https://img.freepik.com/free-vector/world-oceans-day-watercolor-illustration_23-2149391655.jpg?size=626&ext=jpg&ga=GA1.2.1614607020.1683036746",
        "sellerEmail": "seller3@example.com",
        "price": 7.99,
        "subcategory": "Water Toys",
        "rating": 4.4,
        "availableQuantity": 30,
        "detailDescription": "Make bath time fun with the Dancing Dolphin Bath Toy. This floating toy spins and sprays water, adding excitement and entertainment to your child's bath routine."
    },
    {
        "toyName": "Gentle Giraffe Teether",
        "animal": "Giraffe",
        "picture": "https://img.freepik.com/premium-vector/cute-happy-cartoon-giraffe-standing_146562-1.jpg?size=626&ext=jpg&ga=GA1.2.1614607020.1683036746&semt=ais",
        "sellerEmail": "seller3@example.com",
        "price": 6.99,
        "subcategory": "Activity Toys",
        "rating": 4.8,
        "availableQuantity": 20,
        "detailDescription": "Soothe your baby's teething discomfort with the Gentle Giraffe Teether. This BPA-free teething toy features various textures and a gentle squeaker, providing relief and sensory stimulation."
    },
    {
        "toyName": "Jungle Explorer Playset",
        "animal": "Lion",
        "picture": "https://img.freepik.com/premium-vector/cartoon-funny-lion-white_29190-6231.jpg?size=626&ext=jpg&ga=GA1.2.1614607020.1683036746&semt=ais",
        "sellerEmail": "seller1@example.com",
        "price": 29.99,
        "subcategory": "Action Toys",
        "rating": 4.7,
        "availableQuantity": 10,
        "detailDescription": "Embark on a wild jungle adventure with the Jungle Explorer Playset. This interactive playset includes a lion figure, safari jeep, and various jungle accessories, inspiring imaginative play for young explorers."
    },
    {
        "toyName": "Pouncing Pup Interactive Toy",
        "animal": "Dog",
        "picture": "https://img.freepik.com/premium-vector/cartoon-happy-little-dog_29190-4218.jpg?size=626&ext=jpg&ga=GA1.1.1614607020.1683036746&semt=ais",
        "sellerEmail": "seller4@example.com",
        "price": 14.99,
        "subcategory": "Interactive Toys",
        "rating": 4.3,
        "availableQuantity": 18,
        "detailDescription": "Watch your dog's excitement with the Pouncing Pup Interactive Toy. This toy features unpredictable movements and sounds that engage and entertain your furry friend for hours."
    },
    {
        "toyName": "Whisker Wonderland Feather Wand",
        "animal": "Cat",
        "picture": "https://l.facebook.com/l.php?u=https%3A%2F%2Fimg.freepik.com%2Ffree-photo%2Ffunny-cat-3d-illustration_183364-80330.jpg%3Fsize%3D626%26ext%3Djpg%26fbclid%3DIwAR3nOuryVtoXJjUNBiKaWjgomKQEcrmLMSyrVZBm3SUs93XpdF5-XGO99Z0&h=AT2SBIzJFLFdmDIPInm1usceBTwJ3zT1HmsU_xHz3BxpzunI0Sp-IZgQa4foSxACGdhWeIRH0PlOq2egge95yWfAcQfzpn1vlorG97ZHIyO7v0USb6qcVJDdIY-ws6InAyItpg",
        "sellerEmail": "seller2@example.com",
        "price": 8.99,
        "subcategory": "Interactive Toys",
        "rating": 4.6,
        "availableQuantity": 25,
        "detailDescription": "Bring out your cat's natural hunting instincts with the Whisker Wonderland Feather Wand. The dangling feathers mimic prey, providing exercise and mental stimulation for your curious feline."
    },
    {
        "toyName": "Galloping Pony Ride-On",
        "animal": "Horse",
        "picture": "https://img.freepik.com/premium-vector/cute-brown-horse-cartoon_160606-624.jpg?size=626&ext=jpg&ga=GA1.1.1614607020.1683036746&semt=ais",
        "sellerEmail": "seller1@example.com",
        "price": 49.99,
        "subcategory": "Active Toys",
        "rating": 4.9,
        "availableQuantity": 5,
        "detailDescription": "Let your child's imagination run wild with the Galloping Pony Ride-On. With a sturdy design and easy-grip handles, this toy provides endless fun as children pretend to ride their very own pony."
    },
    {
        "toyName": "Roaring Safari Plush Set",
        "animal": "Tiger",
        "picture": "https://img.freepik.com/premium-vector/cute-tiger-cartoon-white-background_43633-12262.jpg?size=626&ext=jpg&ga=GA1.1.1614607020.1683036746&semt=ais",
        "sellerEmail": "seller3@example.com",
        "price": 24.99,
        "subcategory": "Plush Toys",
        "rating": 4.7,
        "availableQuantity": 12,
        "detailDescription": "Embark on a safari adventure with the Roaring Safari Plush Set. This set includes a tiger, lion, elephant, and giraffe plush toys, perfect for imaginative play and cuddles."
    },

    {
        "toyName": "Cuddly Kitty Plush",
        "animal": "Cat",
        "picture": "https://img.freepik.com/free-photo/fun-cat-3d-illustration_183364-80786.jpg?size=626&ext=jpg&fbclid=IwAR36NYZwnhIB7WNbynOYJ-PCqGgLFicxHIQw2xJZ6pQztz0kH5pgYXIFDJw",
        "sellerEmail": "seller2@example.com",
        "price": 12.99,
        "subcategory": "Plush Toys",
        "rating": 4.5,
        "availableQuantity": 20,
        "detailDescription": "This adorable Cuddly Kitty Plush toy is perfect for cat lovers. Made with soft and high-quality materials, it provides hours of cuddling fun for both kids and adults."
    },
    {
        "toyName": "Galloping Unicorn Plush",
        "animal": "Unicorn",
        "picture": "https://img.freepik.com/premium-vector/cartoon-rainbow-unicorn-horse-isolated_29190-5443.jpg?size=626&ext=jpg&ga=GA1.1.1614607020.1683036746&semt=ais",
        "sellerEmail": "seller4@example.com",
        "price": 19.99,
        "subcategory": "Plush Toys",
        "rating": 4.8,
        "availableQuantity": 10,
        "detailDescription": "Let your imagination soar with the Galloping Unicorn Plush. With its rainbow-colored mane and magical horn, this plush toy is sure to bring joy and enchantment to children of all ages."
    },
    {
        "toyName": "Roaring T-Rex",
        "animal": "Dinosaur",
        "picture": "https://img.freepik.com/free-vector/triceratops-dinosaur-white-background_1308-91231.jpg?size=626&ext=jpg&ga=GA1.1.1614607020.1683036746&semt=ais",
        "sellerEmail": "seller2@example.com",
        "price": 14.99,
        "subcategory": "Action Toys",
        "rating": 4.4,
        "availableQuantity": 8,
        "detailDescription": "The Roaring T-Rex Figure is a ferocious and detailed dinosaur toy. It features realistic roaring sounds and movable parts, making it the perfect companion for any dinosaur enthusiast."
    },
    {
        "toyName": "Galloping Horse Plush",
        "animal": "Horse",
        "picture": "https://img.freepik.com/premium-vector/cartoon-brown-horse-running-white-background_29190-5734.jpg?size=626&ext=jpg&ga=GA1.1.1614607020.1683036746&semt=ais",
        "sellerEmail": "seller1@example.com",
        "price": 16.99,
        "subcategory": "Plush Toys",
        "rating": 4.6,
        "availableQuantity": 12,
        "detailDescription": "Saddle up for fun with the Galloping Horse Plush. With its realistic mane and soft fur, this plush toy is perfect for imaginative play and horse-loving kids."
    },
    {
        "toyName": "Roaring Tiger Stuffed Animal",
        "animal": "Tiger",
        "picture": "https://img.freepik.com/premium-vector/cute-tiger-cartoon-white-background_43633-12262.jpg?size=626&ext=jpg&ga=GA1.1.1614607020.1683036746&semt=ais",
        "sellerEmail": "seller3@example.com",
        "price": 18.99,
        "subcategory": "Action Toys",
        "rating": 4.7,
        "availableQuantity": 7,
        "detailDescription": "Get ready for a wild adventure with the Roaring Tiger Stuffed Animal."
    },
    {
        "toyName": "Cuddly Kitty Plush",
        "animal": "Cat",
        "picture": "https://img.freepik.com/premium-vector/cartoon-funny-cat-sitting-white-background_29190-7708.jpg?size=626&ext=jpg&ga=GA1.2.1614607020.1683036746&semt=ais",
        "sellerEmail": "seller3@example.com",
        "price": 12.99,
        "subcategory": "Plush Toys",
        "rating": 4.5,
        "availableQuantity": 20,
        "detailDescription": "This adorable Cuddly Kitty Plush toy is perfect for cat lovers. Made with soft and high-quality materials, it provides hours of cuddling fun for both kids and adults."
    },
    {
        "toyName": "Bouncy Bulldog Ball",
        "animal": "Dog",
        "picture": "https://img.freepik.com/premium-vector/cartoon-happy-dog-white_29190-5561.jpg?size=626&ext=jpg&ga=GA1.1.1614607020.1683036746&semt=ais",
        "sellerEmail": "seller1@example.com",
        "price": 9.99,
        "subcategory": "Interactive Toys",
        "rating": 4.2,
        "availableQuantity": 15,
        "detailDescription": "The Bouncy Bulldog Ball is a durable and interactive toy for dogs. It features a textured surface that massages gums and cleans teeth while providing endless bouncing entertainment for your furry friend."
    },
    {
        "toyName": "Unicorn Plush",
        "animal": "Unicorn",
        "picture": "https://img.freepik.com/free-vector/cute-baby-unicorn-fantasy-character_96037-425.jpg?size=626&ext=jpg&ga=GA1.1.1614607020.1683036746&semt=ais",
        "sellerEmail": "seller2@example.com",
        "price": 19.99,
        "subcategory": "Plush Toys",
        "rating": 4.8,
        "availableQuantity": 10,
        "detailDescription": "Let your imagination soar with the Galloping Unicorn Plush. With its rainbow-colored mane and magical horn, this plush toy is sure to bring joy and enchantment to children of all ages."
    },
    {
        "toyName": "T-Rex Figure",
        "animal": "Dinosaur",
        "picture": "https://img.freepik.com/free-vector/tyrannosaurus-rex-t-rex-cartoon-style_1308-87430.jpg?size=626&ext=jpg&ga=GA1.1.1614607020.1683036746&semt=ais",
        "sellerEmail": "seller4@example.com",
        "price": 14.99,
        "subcategory": "Action Toys",
        "rating": 4.4,
        "availableQuantity": 8,
        "detailDescription": "The Roaring T-Rex Figure is a ferocious and detailed dinosaur toy. It features realistic roaring sounds and movable parts, making it the perfect companion for any dinosaur enthusiast."
    }
]
